-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;


-- Table: public.server_actions

-- DROP TABLE IF EXISTS public.server_actions;

CREATE TABLE IF NOT EXISTS public.server_actions
(
    id integer NOT NULL DEFAULT nextval('serveractions_id_seq'::regclass),
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_id bigint,
    action_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    action_name character varying(255) COLLATE pg_catalog."default",
    action_status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT serveractions_pkey PRIMARY KEY (id),
    CONSTRAINT serveractions_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT server_actions_action_name_check CHECK (action_name::text = ANY (ARRAY['SHUTDOWN'::character varying, 'RESTART'::character varying, 'DELETE_FILE'::character varying, 'GET_CPU_USAGE'::character varying, 'GET_STORAGE_USAGE'::character varying, 'GET_TEMPERATURE'::character varying]::text[])),
    CONSTRAINT server_actions_action_status_check CHECK (action_status::text = ANY (ARRAY['SUCCESS'::character varying, 'FAILED'::character varying, 'PENDING'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.server_actions
    OWNER to postgres;